import type { NormalizationChange } from "./normalize-article";
import { fencedLineMask } from "./footnote-typing";

/**
 * Deterministic heading block IDs and internal-link rewriting.
 *
 * Lens links to headings by a stable block ID rather than by heading text:
 *
 *   ## Heading text ^stable-id
 *   [[#^stable-id]]                  (unlabeled — heading targets only)
 *   [[#^stable-id|Custom label]]     (labeled — required for non-headings)
 *
 * The ID is derived from the heading's first few words once, at import, and is
 * never regenerated afterwards: the whole point is that the heading text may
 * later be reworded without breaking the links pointing at it. An ID already
 * present on a heading is therefore always preserved verbatim.
 *
 * Heading-text fragments (`[label](#heading-text)`, `[[#Heading text]]`) are
 * exactly what this replaces — they break on the first rename — so this pass
 * converts every one it can resolve and leaves the rest for the validator and
 * the LLM reviewer. Empty `[label](#)` links carry no recoverable destination
 * and are demoted to plain text, per the same rule.
 *
 * Ordering note: this runs after `localizeSelfFragments` (DOM stage), which has
 * already resolved provable self-fragments to `#<lens-slug>` form. That slug is
 * the join key here, so the two stages compose: the DOM stage decides *which*
 * heading a link means, this stage decides *how* to address it.
 *
 * Idempotent: headings that already carry an ID are left alone, and links
 * already in `[[#^id]]` form are not matched by the rewrite patterns.
 */

export interface HeadingAnchorResult {
  body: string;
  changes: NormalizationChange[];
}

/** Words taken from the heading text to build an ID. */
const ID_WORD_COUNT = 4;
const ID_MAX_CHARS = 40;

const ATX_RE = /^(\s{0,3}#{1,6})\s+(.*?)\s*$/;
const TRAILING_ID_RE = /\s+\^([A-Za-z0-9-]+)$/;

/** Lens Platform's rendered heading id (mirrors `renderedHeadingId` in
 * lens-platform content_processor/src/validator/article-structure.ts). Kept in
 * sync with the copy in normalize-dom.ts, which produces the `#<slug>` links
 * this pass consumes. */
function lensHeadingSlug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 50);
}

/** Strip inline Markdown so heading text and link labels compare as prose. */
function plainText(markdown: string): string {
  return markdown
    .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
    .replace(/\[\[#\^[A-Za-z0-9-]+\|([^\]]*)\]\]/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_`]+/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/** An ID built from the heading's leading words: letters, numbers, hyphens. */
function candidateId(headingText: string): string {
  const words = plainText(headingText)
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter(Boolean);
  const id = words
    .slice(0, ID_WORD_COUNT)
    .join("-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, ID_MAX_CHARS)
    .replace(/-$/, "");
  return id || "section";
}

interface HeadingRecord {
  id: string;
  text: string;
}

interface HeadingScan {
  headings: HeadingRecord[];
  /** IDs written in the source, as opposed to generated by this pass. Only
   * these resolve a `#fragment` by ID alone: a generated ID is a slug of the
   * heading text, so matching one verbatim proves nothing that the slug lookup
   * does not already prove — and would silently resolve an ambiguous slug to
   * whichever heading happened to be numbered first. */
  authored: Set<string>;
}

/** Assign block IDs to every heading, preserving any already present. */
function assignHeadingIds(
  lines: string[],
  fenced: boolean[],
  record: (code: string, before: string, after: string) => void,
): HeadingScan {
  const used = new Set<string>();
  const authored = new Set<string>();
  const headings: HeadingRecord[] = [];

  // Existing IDs are reserved before any are generated, so a generated ID can
  // never collide with one that links already point at.
  for (let i = 0; i < lines.length; i++) {
    if (fenced[i]) continue;
    const atx = ATX_RE.exec(lines[i]);
    if (!atx) continue;
    const existing = TRAILING_ID_RE.exec(atx[2]);
    if (existing) {
      used.add(existing[1]);
      authored.add(existing[1]);
    }
  }

  for (let i = 0; i < lines.length; i++) {
    if (fenced[i]) continue;
    const atx = ATX_RE.exec(lines[i]);
    if (!atx) continue;
    const [, hashes, rest] = atx;

    const existing = TRAILING_ID_RE.exec(rest);
    if (existing) {
      headings.push({ id: existing[1], text: rest.slice(0, existing.index).trim() });
      continue;
    }

    const text = rest.trim();
    if (!text) continue;

    const base = candidateId(text);
    let id = base;
    for (let n = 2; used.has(id); n++) id = `${base}-${n}`;
    used.add(id);

    const before = lines[i];
    lines[i] = `${hashes} ${text} ^${id}`;
    record("normalize.heading-block-id", before, lines[i]);
    headings.push({ id, text });
  }

  return { headings, authored };
}

/** Rewrite outside inline code spans only. */
function outsideCode(line: string, rewrite: (chunk: string) => string): string {
  return line
    .split(/(`+[^`]*`+)/)
    .map((part, i) => (i % 2 === 0 ? rewrite(part) : part))
    .join("");
}

/** Deterministic heading IDs + internal link rewriting. See module docs. */
export function applyHeadingAnchors(body: string): HeadingAnchorResult {
  const changes = new Map<string, NormalizationChange>();
  const record = (code: string, before: string, after: string) => {
    const change = changes.get(code) ?? { code, count: 0, samples: [] };
    change.count += 1;
    if (change.samples.length < 5) change.samples.push({ before, after });
    changes.set(code, change);
  };

  const lines = body.split("\n");
  const fenced = fencedLineMask(lines);
  const { headings, authored } = assignHeadingIds(lines, fenced, record);

  // Resolution keys. A key that two headings share is dropped rather than
  // guessed at — an ambiguous link is left for the reviewer to judge.
  const bySlug = new Map<string, string | null>();
  const byText = new Map<string, string | null>();
  const add = (map: Map<string, string | null>, key: string, id: string) => {
    if (!key) return;
    map.set(key, map.has(key) ? null : id);
  };
  for (const h of headings) {
    const plain = plainText(h.text);
    add(bySlug, lensHeadingSlug(plain), h.id);
    add(byText, plain.toLowerCase(), h.id);
  }

  const resolve = (fragment: string): string | null => {
    const raw = fragment.trim();
    if (!raw) return null;
    if (authored.has(raw)) return raw;
    let decoded = raw;
    try {
      decoded = decodeURIComponent(raw);
    } catch {
      /* use the raw fragment */
    }
    return (
      bySlug.get(lensHeadingSlug(decoded)) ??
      byText.get(decoded.toLowerCase()) ??
      bySlug.get(lensHeadingSlug(decoded.replace(/-/g, " "))) ??
      null
    );
  };

  /** `[[#^id]]` when the label just repeats the heading, labeled otherwise.
   * The match is case-sensitive on purpose: an unlabeled link renders the
   * heading's own text, so dropping a label that differs only in case would
   * capitalize a word mid-sentence ("See the risks" → "See The risks"). */
  const link = (id: string, label: string): string => {
    const heading = headings.find((h) => h.id === id);
    const plain = plainText(label);
    if (!plain) return `[[#^${id}]]`;
    if (heading && plain === plainText(heading.text)) return `[[#^${id}]]`;
    return `[[#^${id}|${plain}]]`;
  };

  for (let i = 0; i < lines.length; i++) {
    if (fenced[i]) continue;
    const before = lines[i];

    lines[i] = outsideCode(lines[i], (chunk) => {
      let out = chunk;

      // `[[#Heading text]]` / `[[#Heading text|label]]` — never `[[#^id]]`.
      out = out.replace(
        /\[\[#(?!\^)([^\]|\n]+)(?:\|([^\]\n]*))?\]\]/g,
        (whole, target: string, label?: string) => {
          const id = resolve(target);
          return id ? link(id, label ?? target) : whole;
        },
      );

      // `[label](#fragment)` and empty `[label](#)`.
      out = out.replace(
        /(!?)\[([^\]\n]*)\]\(#([^)\s]*)\)/g,
        (whole, bang: string, label: string, fragment: string) => {
          if (bang) return whole;
          if (!fragment) return plainText(label) || whole;
          const id = resolve(fragment);
          return id ? link(id, label) : whole;
        },
      );

      return out;
    });

    if (lines[i] === before) continue;
    if (/\]\(#\)/.test(before)) record("normalize.empty-fragment-link", before, lines[i]);
    else record("normalize.heading-fragment-link", before, lines[i]);
  }

  return { body: lines.join("\n"), changes: [...changes.values()] };
}
