import { test, expect } from '@playwright/test';

// Helper: wait for the app to load (share token required — use local relay)
// These tests assume:
//   1. Local relay server is running on port 8190
//   2. Vite dev server is running on port 5273 with VITE_LOCAL_RELAY=true
//   3. A valid share link URL is used (generated by generate-share-link.ts)
//
// The baseURL in playwright.config.ts should be the full share link URL,
// or we navigate to it explicitly in beforeEach.

// Panel selectors — all panels use custom CSS flexbox with pixel widths
const PANELS = {
  leftSidebar: '#sidebar',
  rightSidebar: '#right-sidebar',
  commentMargin: '#comment-margin',
  discussion: '#discussion',
  editor: '#editor',
  editorArea: '#editor-area',  // now a plain CSS flexbox div
  appOuter: '#app-outer',
};

// Toggle button selectors (by title attribute)
const TOGGLES = {
  leftSidebar: 'button[title="Toggle left sidebar"]',
  rightSidebar: 'button[title="Toggle right sidebar"]',
  commentMargin: 'button[title="Toggle comments"]',
  discussion: 'button[title="Toggle discussion"]',
};

/** Check if a panel is visually collapsed (0px width or display:none) */
async function isCollapsed(page: import('@playwright/test').Page, selector: string): Promise<boolean> {
  const el = page.locator(selector);
  // Panel may not exist in DOM (e.g., discussion when no Discord channel)
  if (await el.count() === 0) return true;
  const box = await el.boundingBox();
  if (!box) return true;
  return box.width < 2; // collapsed panels have 0% flex-grow → 0px width
}

test.describe('Panel collapse/expand', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the app — assumes share link is configured via baseURL or env
    await page.goto('/');
    // Wait for the editor to be ready
    await page.waitForSelector(PANELS.editor, { timeout: 15_000 });
    // Give panels a moment to settle initial layout
    await page.waitForTimeout(500);
  });

  test('1. Initial state: left sidebar, right sidebar, comment margin visible; discussion hidden', async ({ page }) => {
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(false);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(false);
    expect(await isCollapsed(page, PANELS.commentMargin)).toBe(false);
    // Discussion starts collapsed (initial state in desiredCollapsedRef)
    expect(await isCollapsed(page, PANELS.discussion)).toBe(true);
  });

  test('2. Toggle left sidebar: click toggle -> hidden, click again -> visible', async ({ page }) => {
    // Collapse
    await page.click(TOGGLES.leftSidebar);
    await page.waitForTimeout(300); // wait for animation
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(true);

    // Expand
    await page.click(TOGGLES.leftSidebar);
    await page.waitForTimeout(300);
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(false);
  });

  test('3. Toggle right sidebar: click toggle -> hidden, click again -> visible', async ({ page }) => {
    // Collapse
    await page.click(TOGGLES.rightSidebar);
    await page.waitForTimeout(300);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(true);

    // Expand
    await page.click(TOGGLES.rightSidebar);
    await page.waitForTimeout(300);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(false);
  });

  test('4. Narrow viewport to 800px -> both sidebars collapse', async ({ page }) => {
    // Start wide
    await page.setViewportSize({ width: 1400, height: 800 });
    await page.waitForTimeout(500);

    // Verify both are expanded at wide width
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(false);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(false);

    // Narrow below sidebar threshold (850px)
    await page.setViewportSize({ width: 800, height: 800 });
    await page.waitForTimeout(500);

    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(true);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(true);
  });

  test('5. Widen viewport to 1200px -> both sidebars re-expand (auto-expand)', async ({ page }) => {
    // Start wide
    await page.setViewportSize({ width: 1400, height: 800 });
    await page.waitForTimeout(500);

    // Narrow to trigger auto-collapse
    await page.setViewportSize({ width: 800, height: 800 });
    await page.waitForTimeout(500);

    // Confirm collapsed
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(true);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(true);

    // Widen back past expand threshold (900 + hysteresis)
    await page.setViewportSize({ width: 1200, height: 800 });
    await page.waitForTimeout(500);

    // THIS IS THE BUG: right sidebar should re-expand but doesn't
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(false);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(false);
  });

  test('6. Narrow to 1050px -> discussion collapses, sidebars remain', async ({ page }) => {
    // First expand discussion
    await page.click(TOGGLES.discussion);
    await page.waitForTimeout(300);

    // Start wide so discussion is visible
    await page.setViewportSize({ width: 1400, height: 800 });
    await page.waitForTimeout(500);
    expect(await isCollapsed(page, PANELS.discussion)).toBe(false);

    // Narrow below discussion threshold (1100) but above sidebar threshold (850)
    await page.setViewportSize({ width: 1050, height: 800 });
    await page.waitForTimeout(500);

    expect(await isCollapsed(page, PANELS.discussion)).toBe(true);
    expect(await isCollapsed(page, PANELS.leftSidebar)).toBe(false);
    expect(await isCollapsed(page, PANELS.rightSidebar)).toBe(false);
  });

  test('7. Widen back to 1200px -> discussion re-expands', async ({ page }) => {
    // First expand discussion
    await page.click(TOGGLES.discussion);
    await page.waitForTimeout(300);

    // Start wide
    await page.setViewportSize({ width: 1400, height: 800 });
    await page.waitForTimeout(500);
    expect(await isCollapsed(page, PANELS.discussion)).toBe(false);

    // Narrow to collapse discussion
    await page.setViewportSize({ width: 1050, height: 800 });
    await page.waitForTimeout(500);
    expect(await isCollapsed(page, PANELS.discussion)).toBe(true);

    // Widen past discussion expand threshold (1150)
    await page.setViewportSize({ width: 1200, height: 800 });
    await page.waitForTimeout(500);

    expect(await isCollapsed(page, PANELS.discussion)).toBe(false);
  });
});
